-- Enable extensions for scheduling and HTTP requests if available
CREATE EXTENSION IF NOT EXISTS pg_net;
CREATE EXTENSION IF NOT EXISTS pg_cron;
-- 1. Sunday Attendance Summary
-- Invokes edge function which dynamically loads the pastor email and configured schedule from app_settings
--
-- SELECT cron.schedule(
--   'sunday-attendance-summary',
--   '20 17 * * 0',
--   $$
--   SELECT net.http_post(
--     url := 'https://rntxinxyttftzhlxpucr.supabase.co/functions/v1/attendance-summary',
--     headers := '{"Content-Type": "application/json", "Authorization": "Bearer YOUR_SERVICE_ROLE_KEY"}'::jsonb,
--     body := '{"type": "sunday"}'::jsonb
--   ) AS request_id;
--   $$
-- );
-- 2. Monthly Attendance Breakdown at the end of every month
-- Invokes edge function which dynamically loads the pastor email from app_settings
--
-- SELECT cron.schedule(
--   'monthly-attendance-summary',
--   '0 21 28-31 * *',
--   $$
--   SELECT net.http_post(
--     url := 'https://rntxinxyttftzhlxpucr.supabase.co/functions/v1/attendance-summary',
--     headers := '{"Content-Type": "application/json", "Authorization": "Bearer YOUR_SERVICE_ROLE_KEY"}'::jsonb,
--     body := '{"type": "monthly"}'::jsonb
--   ) AS request_id;
--   $$
-- );